spring:
  serlet:
    multipart:
      location: ${user.dir}
  security:
    user:
      name: ${security.username}
      password: ${security.password}
  zipkin:
    baseUrl: http://zipkin/ #所有的数据提交到此服务之中
  sleuth:
    sampler:
     percentage: 0.1 #定义抽样比率，默认为0.1
  cloud:
    loadbalancer:
      retry:
        enabled: true

swagger2:
  enabled: true
  title : ${spring.application.name}
  apiName: Authorization
  apiKeyName: Authorization

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    service-url:
      defaultZone: ${registry.uri}

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 65000

#隔离策略，有THREAD和SEMAPHORE
#THREAD - 它在单独的线程上执行，并发请求受线程池中的线程数量的限制
#SEMAPHORE - 它在调用线程上执行，并发请求受到信号量计数的限制
#默认使用THREAD模式，以下几种场景可以使用SEMAPHORE模式：
#只想控制并发度
#外部的方法已经做了线程隔离
#调用的是本地方法或者可靠度非常高、耗时特别小的方法（如redis）


#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: Semaphore #一个线程内能拿到 auth token

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  #OkToRetryOnAllOperations: true  #默认为false,则只允许GET请求被重试
  #retryableStatusCodes: 404,502 返回404,502的时候，进行重试，其他状态码不重试
  #ribbonTimeout = (ribbon.ConnectTimeout + ribbon.ReadTimeout) * (ribbon.MaxAutoRetries + 1) * (ribbon.MaxAutoRetriesNextServer + 1);


management:
  endpoints:
    web:
      exposure:
        include: "*" #加载所有的端点，默认只加载了info、health
  endpoint:
    health:
      show-details: always
    shutdown:  #可以关闭指定的端点
      enabled: false

info:
  swaggerUrl: http://ip:${server.port}/swagger-ui.html#
  druidMonitor: http://ip:${server.port}/druid/index.html