server:
  port: 8080

spring:
  zipkin:
    enabled: true
  datasource:
    url: jdbc:mysql://10.12.40.224:3306/openplatform?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: onlineDB
    password: bo28jsl29a
#    url: jdbc:mysql://localhost:3306/openplatform?useSSL=false&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 123456
    driverClassName: com.mysql.jdbc.Driver
#  kafka:
#    bootstrap-server: 10.12.51.187:6667
  cloud:
    stream:
      default:
        producer:
          headerMode: embeddedHeaders
        consumer:
          headerMode: embeddedHeaders
      bindings:
        springCloudBusInput:
          destination: GATEWAY_NODE_SETTING
#          group:
        springCloudBusOutput:
          destination: GATEWAY_NODE_SETTING
      kafka:
        binder:
          autoCreateTopics: false
          brokers: 10.12.51.187:6667
          zkNodes: ${kafka.zookeeper.quorum}

swagger2:
  gateway: true
  serviceSources:
    account: 账户服务
    console: 开放平台前台
    manage: 开放平台后台

security:
  oauth2:
    client:
      clientId: inner_service
      clientSecret: 123456
    resource:
      tokenInfoUri: ${uaa.uri}/oauth/check_token
      white-list:
        emptyPrefix:
          swaggerUrl: default
        uaa:
          httpAllMethod: /**
        account:
          swaggerUrl: default
          httpGet: /user/duplicate/username/*,/user/duplicate/email/*,/user/contact/*,/code
          httpPost: /user,/mail/register,/mail/forget/*,/code
          httpPut:  /user/forget
          httpAllMethod: /client/*
        console:
          swaggerUrl: default
          httpAllMethod: /user/**,/test/**,/open/**,/diyapplyProduct/findPagedApps,/guideConsole/guideList,/guideConsole/guide/**,/api/showApiList,/api/showApi,/api/showDocApiList,/monitor/**,/dubboInfo/**,/dubboDateController/manualUpdataData,/data/migra/**,/statistics/**,/document/**,/static/file/*
        manage:
          swaggerUrl: default
          httpAllMethod: /admin/**,/test/**,/route/**,/apiBulk/exportApis

zuul:
  SendErrorFilter:
    error:
      disable : true
  retryable: true  #zuul.routes.<routename>.retryable=true
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  sensitiveHeaders:
  ignored-patterns: /account/client/*
  routes:
    service-auth:
      path: /uaa/**
    service-account:
      path: /account/**
    service-openapi-console:
      path: /console/**
    service-openapi-manage:
      path: /manage/**
    allPath:
      path: /aaa
      url: http://localhost:8080/uaa/oauth/token
    allPath1:
      path: /1
      url: http://10.12.51.210/account/user
#    b-services:
#      path: /b/**
#      sensitiveHeaders:
#    user-route:      # 该配置方式中，user-route只是给路由一个名称，可以任意起名。
#     url:http://localhost:8000/  # 指定的url
#     path: /user/**      # url对应的路径。