server:
  port: 8080

spring:
  zipkin:
      enabled: true

swagger2:
  gateway: true
  serviceSources:
    marketing: 营销服务
    datacentre: 会员服务

zuul:
  SendErrorFilter:
    error:
      disable : true
  retryable: true  #zuul.routes.<routename>.retryable=true
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    service-datacentre:
      path: /datacentre/**
    service-marketing:
      path: /marketing/**
#    b-services:
#      path: /b/**
#      sensitiveHeaders:
#    user-route:      # 该配置方式中，user-route只是给路由一个名称，可以任意起名。
#     url:http://localhost:8000/  # 指定的url
#     path: /user/**      # url对应的路径。