server:
  port: 8002

swagger2:
  enabled: false

spring:
  zipkin:
    enabled: false
#spring:
#  boot:
#    admin:
#      notify:
#        mail:
#          to: XXXXX@163.com  # 邮件接收方
#          from: XXXXX@qq.com  # 邮件发送方
#  mail:
#    host: smtp.qq.com   # qq邮箱服务器主机host，需要在QQ邮箱设置中开启smtp协议 163邮箱为smtp.163.com
#    username: XXXXX@qq.com  # qq邮箱账号
#    password: XXXXXXXXXX  # 第三方登录的授权码
#    common:
#      mail.debug: false
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true
#      mail.smtp.ssl.enable: true

# <dependency>
#      <groupId>org.springframework.boot</groupId>
#      <artifactId>spring-boot-starter-mail</artifactId>
#  </dependency>