server:
  port: 8012

pagehelper:
  supportMethodsArguments: true
  pageSizeZero: true
  reasonable: true
  helperDialect: mysql
  params: count=countSql

mybatis:
  mapperLocations: classpath*:cn/ce/**/mapper/*.xml
  scanPackages: cn.ce.**.dao
  typeAliasesPackage: cn.ce.**.entity

security:
  oauth2:
    resource:
#      id: inner_service
#      userInfoUri: http://localhost:8011/oauth/current
#      prefer-token-info: false
      tokenInfoUri: http://localhost:8011/oauth/check_token
#      filter-order: 3
    client:
      clientId: inner_service
      clientSecret: 123456
#      accessTokenUri: http://localhost:8011/oauth/token
#      userAuthorizationUri: http://localhost:8011/oauth/authorize

spring:
  zipkin:
    enabled: true
  resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  transaction:
    default-timeout: 60s
    rollback-on-commit-failure: true
  mail:
    host: smtp.300.cn
    port: 25
    sender: sla@300.cn
    username: sla@300.cn
    password: Q1w2e3r4
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
  cache:
    type: redis
  redis:
    host: 10.12.40.82
    password: 12345
    port: 6379
    lettuce:
      pool:
        max-active: 20
        min-idle: 0
        max-wait: 10s
        max-idle: 20
  datasource:
    url: jdbc:mysql://10.12.40.224:3306/auth_centre?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: onlineDB
    password: bo28jsl29a
#    url: jdbc:mysql://localhost:3306/auth_centre?useSSL=false&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      minIdle: 5
      useGlobalDataSourceStat: true
      validationQuery: SELECT 1 FROM DUAL
      initialSize: 5
      maxWait: 60000
      filters: stat,wall,slf4j
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      testWhileIdle: true
      testOnBorrow: false
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      testOnReturn: false
      maxActive: 20
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        loginUsername: ${spring.security.user.name}
        loginPassword: ${spring.security.user.password}
        resetEnable: true