server:
  port: 8011
#  servlet:
#    context-path: /uaa

pagehelper:
  supportMethodsArguments: true
  pageSizeZero: true
  reasonable: true
  helperDialect: mysql
  params: count=countSql

mybatis:
  mapperLocations: classpath*:cn/ce/**/mapper/*.xml
  scanPackages: cn.ce.**.dao
  typeAliasesPackage: cn.ce.**.entity

swagger2:
  enabled: false

spring:
  zipkin:
    enabled: true
  resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  transaction:
    default-timeout: 60s
    rollback-on-commit-failure: true
  cache:
    type: redis
  redis:
    host: 10.12.40.82
    password: 12345
    port: 6379
    lettuce:
      pool:
        max-active: 20
        min-idle: 0
        max-wait: 10s
        max-idle: 20
  datasource:
    url: jdbc:mysql://10.12.40.224:3306/auth_centre?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: onlineDB
    password: bo28jsl29a
    driverClassName: com.mysql.jdbc.Driver

