server:
  port: 8013
  staticAccessPath: /static/file/
  uploadFolder: /uploadFiles/
#pagehelper:
#  supportMethodsArguments: true
#  pageSizeZero: true
#  reasonable: true
#  helperDialect: mysql
#  params: count=countSql

#classpath*  这个*可以读取到jar包内部的xml
mybatis:
  mapperLocations: classpath*:cn/ce/**/mapper/*.xml
  scanPackages: cn.ce.**.dao
  typeAliasesPackage: cn.ce.**.entity

#security:
#  oauth2:
#    client:
#      clientId: inner_service
#      clientSecret: 123456
#    resource:
#      tokenInfoUri: http://service-auth/oauth/check_token
#      white-list:
#        swaggerUrl: default
#        httpAllMethod: /user/**,/test/**,/open/**,/diyapplyProduct/findPagedApps,/guideConsole/guideList,/guideConsole/guide/**,/api/showApiList,/api/showApi,/api/showDocApiList,/monitor/**,/dubboInfo/**,/dubboDateController/manualUpdataData,/data/migra/**,/statistics/**,/document/**,/static/file/*

spring:
  zipkin:
    enabled: false
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  transaction:
    default-timeout: 60s
    rollback-on-commit-failure: true
  cache:
    type: redis
  redis:
    host: 10.12.40.82
    password: 12345
    port: 6379
    lettuce:
      pool:
        max-active: 20
        min-idle: 0
        max-wait: 10s
        max-idle: 20
  datasource:
    url: jdbc:mysql://10.12.40.224:3306/openplatform?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: onlineDB
    password: bo28jsl29a
#    url: jdbc:mysql://localhost:3306/auth_centre?useSSL=false&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      minIdle: 5
      useGlobalDataSourceStat: true
      validationQuery: SELECT 1 FROM DUAL
      initialSize: 5
      maxWait: 60000
      filters: stat,wall,slf4j
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      testWhileIdle: true
      testOnBorrow: false
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      testOnReturn: false
      maxActive: 20
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        loginUsername: ${spring.security.user.name}
        loginPassword: ${spring.security.user.password}
        resetEnable: true

mail:
  nick: 信息化研发部
  server: smtp.300.cn
  password: xxh@
  protocol: smtp
  user: xxh@300.cn
dubbo:
  node: /dubbo-upgrade,/dubbo-debug
registerBathApp: http://10.12.40.94:9000/app/registerBathApp?tenantId=#{tId}&apps=#{appList}
dubbo_app_interfaceurl: http://10.12.40.94:9000/app/findAppsByUnit?unit=#{unit}
registerMenu: http://test.300.cn/api-platform/openapi/registerMenu
box_getPool: http://10.12.40.83:8080/webportal-webapp-1.0-SNAPSHOT/hcluster/getBypool
productMenuList: http://test.300.cn/api-platform/openapi/productMenuList?bossInstanceCode={bossInstanceCode}
getProjectsList: http://10.12.51.84:7788/v1/projects
checkTicket: http://10.12.40.161:8088/passport/checkTicket
findPagedApps: http://10.12.40.94:9000/app/findPagedApps?owner=#{o}&name=#{n}&pageNum=#{p}&pageSize=#{z}&appType=1
deleteMenu1: http://10.12.40.94:9000/menu/deleteCustomerMenuByIds?ids={ids}
findTenantAppsByTenantKeypage: http://10.12.40.94:9000/findTenantAppsByTenantKeyAndAppName?key=#{key}&appName=#{n}&pageSize=#{z}&pageNum=#{p}
saveOrUpdateApps: http://10.12.40.94:9000/app/saveOrUpdateApps?apps=#{apps}
zookeeper:
  connection: 10.12.40.189:2181,10.12.40.189:2182,10.12.40.189:2183
findAppsById: http://10.12.40.94:9000/app/findAppsByIds?appIds=#{apiIds}
getProviders: http://10.12.40.94:9000/unit/getProviders
taskExecutor:
  corePoolSize: 5
  queueCapacity: 20
  maxPoolSize: 10
  keepAliveSeconds: 200
registerMenu1: http://10.12.40.94:9000/menu/saveOrUpdateCustomerMenus?tenantId={tenantId}
productMenuList1: http://10.12.40.94:9000/menu/findMemu?tenantId={tenantId}
es:
  path: 10.12.40.161
menuMonitor: http://test.300.cn/api-platform/openapi/productMenuList?bossInstanceCode=monitor
findTenantAppsByTenantKey: http://10.12.40.94:9000/findTenantAppsByTenantKey?key=#{key}
ois_openApply: http://10.12.40.170:5554/ois/v1/openApplication
environment: test
box_delete: http://10.12.40.83:8080/webportal-webapp-1.0-SNAPSHOT/gce/delSandbox?
ois_api: http://10.12.40.170:5554/ois/v1/api
box_add: http://10.12.40.83:8080/webportal-webapp-1.0-SNAPSHOT/gce/addSandbox
box_state: http://10.12.40.83:8080/webportal-webapp-1.0-SNAPSHOT/gce/checkStatus?sandboxname=#{sandboxname}&resourcePool=#{resourcePool}
ois_diyApply: http://10.12.40.170:5554/ois/v1/customApplication
generatorTenantKey: http://10.12.40.94:9000/generatorTenantKey?id=#{TenantKeyid}
findMemberInfoByMemberCode: http://test-api-console.300.cn/api-portal/rmi/member/get?param=
findWebListByCustId: http://10.12.40.94:9000/findTenantByCusIdAndGroupId?cusId=
findTenatById: http://10.12.40.94:9000/getTenantById?id=